[theme]
base="light"

# soft grey background
backgroundColor="#EBEBEB"
secondaryBackgroundColor="#F3F3F3"

# text colors
textColor="#111827"

# nice slate accent
primaryColor="#6B7280"

font="sans serif"
