[theme]
base="light"

# soft grey background
backgroundColor="#F3F3F3"
secondaryBackgroundColor="#FFFFFF"

# text colors
textColor="#111827"

# nice slate accent
primaryColor="#6B7280"

font="sans serif"
